server {
    listen 8080;
    root /var/www/html/public;
    index index.php;

    # Desabilita access log para eliminar I/O de disco das medições
    access_log off;
    error_log /var/log/nginx/error.log warn;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass          app-a:9000;
        fastcgi_index         index.php;
        fastcgi_param         SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout  60s;
        include               fastcgi_params;
    }

    location ~ /\. {
        deny all;
    }
}
